package uk.vitalcode.events.cambridge

import uk.vitalcode.events.model._

object CambridgeScienceCentre {
    val page: Page = PageBuilder()
        .setId("cambridgeScienceCentre:list")
        .setUrl("http://www.cambridgesciencecentre.org/whats-on/events-calendar/")
        .addPage(PageBuilder()
            .isRow(true)
            .setId("cambridgeScienceCentre:description")
            .setLink("div.lst-Body section.lst-Plain_Item a.lst-Plain_TitleAction")
            .addPage(PageBuilder()
                .setId("cambridgeScienceCentre:image")
                .setLink("section.pg-Content figure.wys-IntroImage img")
                .addProp(PropBuilder()
                    .setName("image")
                    .setKind(PropType.Image)
                )
            )
            .addProp(PropBuilder()
                .setName("title")
                .setCss("div.pg-SimpleHero_Inner h1.pg-SimpleHero_Title")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("description")
                .setCss("section.pg-Content div.wys-WYSIWYG > p")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("cost")
                .setCss("div.pg-SimpleHero_Body > div.pg-SimpleHero_Meta p.met-Item:nth-child(4)")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("when")
                .setCss("div.pg-SimpleHero_InfoOuter div.pg-SimpleHero_InfoItem:nth-child(1) > p.pg-SimpleHero_InfoItemValue, div.pg-SimpleHero_InfoOuter div.pg-SimpleHero_InfoItem:nth-child(3) > p.pg-SimpleHero_InfoItemValue")
                .setKind(PropType.Date)

            )
            .addProp(PropBuilder()
                .setName("venue")
                .setValue("Cambridge Science Centre, 18 Jesus Lane, Cambridge, CB5 8BQ")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("venue-category")
                .setValue(Category.FAMILY)
                .setKind(PropType.Text)
            )
        )
        .addPage(PageBuilder()
            .setRef("cambridgeScienceCentre:list")
            .setId("cambridgeScienceCentre:pagination")
            .setLink("div.lyt-Content-singleColumn div.pgn-Pagination a.pgn-Control-next")
        )
        .build()
}
