package uk.vitalcode.events.cambridge

import uk.vitalcode.events.model._

object CambridgeScienceCentre {
    val page: Page = PageBuilder()
        .setId("cambridgeScienceCentre:list")
        .setUrl("http://www.cambridgesciencecentre.org/whats-on/events-calendar/")
        .addPage(PageBuilder()
            .isRow(true)
            .setId("cambridgeScienceCentre:description")
            .setLink("div.main_wrapper > section > article > ul > li > h2 > a")
            .addPage(PageBuilder()
                .setId("cambridgeScienceCentre:image")
                .setLink("section.event_detail > div.page_content > article > img")
                .addProp(PropBuilder()
                    .setName("image")
                    .setKind(PropType.Image)
                )
            )
            .addProp(PropBuilder()
                .setName("title")
                .setCss("div.main_wrapper > section.event_detail > div.information > h1")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("description")
                .setCss("div.main_wrapper > section.event_detail > div.page_content p:nth-child(4)")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("cost")
                .setCss("div.main_wrapper > section.event_detail > div.page_content p:nth-child(5)")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("when")
                .setCss("div.main_wrapper > section.event_detail > div > span:nth-child(2)")
                .setKind(PropType.Date)

            )
            .addProp(PropBuilder()
                .setName("venue")
                .setValue("Cambridge Science Centre, 18 Jesus Lane, Cambridge, CB5 8BQ")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("venue-category")
                .setValue(Category.FAMILY)
                .setKind(PropType.Text)
            )
        )
        .addPage(PageBuilder()
            .setRef("cambridgeScienceCentre:list")
            .setId("cambridgeScienceCentre:pagination")
            .setLink("div.pagination > div.omega > a")
        )
        .build()
}
