package uk.vitalcode.events.cambridge

import uk.vitalcode.events.model.{Page, PageBuilder, PropBuilder, _}

object FamilyGuideToCambridge {
    val page: Page = PageBuilder()
        .setId("familyGuideToCambridge:list")
        .setUrl("http://familyguideto.co.uk/whats-on-2")
        .addPage(PageBuilder()
            .isRow(true)
            .setId("familyGuideToCambridge:description")
            .setLink("#mainCol .ProductListMain > ol.productList > li > .centerBlock > h2 > a")
            .addPage(PageBuilder()
                .setId("familyGuideToCambridge:image")
                .setLink("#mainCol .tabContainer .overviewLeft  .image:nth-child(1) > img")
                .addProp(PropBuilder()
                    .setName("image")
                    .setKind(PropType.Image)
                )
            )
            .addProp(PropBuilder()
                .setName("title")
                .setCss("#showInfoWrapper > .showInfo > h1")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("description")
                .setCss("#showInfoWrapper >.showInfo > p:nth-child(3), .column550RightPad > .darkGreyBg > p")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("cost")
                .setCss(".column310NoPad > .column310NoPad >.lightGreyBg >p:nth-child(4)")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("when")
                .setCss("#showInfoWrapper .selectWrapper > select > option")
                .setKind(PropType.Date)
            )
            .addProp(PropBuilder()
                .setName("venue")
                .setValue("ADC Theatre, Park Street, Cambridge, CB5 8AS")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("venue-category")
                .setValue(Category.THEATRE)
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("telephone")
                .setValue("01223 300085")
                .setKind(PropType.Text)
            )
        )
        .build()
}
