package uk.vitalcode.events.cambridge

import uk.vitalcode.events.model._

object Junction {
    val page: Page = PageBuilder()
        .setId("junction:list")
        .setUrl("http://www.junction.co.uk/events/all-events")
        .addPage(PageBuilder()
            .isRow(true)
            .setId("junction:description")
            .setLink("#events-list-home .views-row .callouts a:nth-child(1)")
            .addPage(PageBuilder()
                .setId("junction:image")
                .setLink("#event-image ul.bxslider > li:nth-child(1) > img")
                .addProp(PropBuilder()
                    .setName("image")
                    .setKind(PropType.Image)
                )
            )
            .addProp(PropBuilder()
                .setName("title")
                .setCss("#event-inner > .row:nth-child(1) h3 > strong")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("description")
                .setCss("#block-views-event-tabs-block .tab-inner > p")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("cost")
                .setCss("#event-inner > .row:nth-child(3) > div:nth-child(2)")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("when")
                .setCss("#event-inner > .row:nth-child(2) > div")
                .setKind(PropType.Date)

            )
            .addProp(PropBuilder()
                .setName("venue")
                .setValue("Cambridge Junction, Clifton Way, Cambridge, CB1 7GX")
                .setKind(PropType.Text)
            )
            .addProp(PropBuilder()
                .setName("venue-category")
                .setValue(Category.THEATRE)
                .setKind(PropType.Text)
            )
        )
        .build()
}
